In [1]:
import numpy as np

### 1 - Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [2]:
a = np.arange (12, 24)
print (a)

[12 13 14 15 16 17 18 19 20 21 22 23]


### 2 - Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [3]:
a.reshape(3, 4)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [4]:
a.reshape(4, 3)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [5]:
a.reshape(2, 6)

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [6]:
a.reshape(6, 2)

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [7]:
a.resize(12, 1)
print (a)

[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


### 3- Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [8]:
a.reshape(6, -1)

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [9]:
np.reshape(a, (4, -1))

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [10]:
np.reshape(a, (3, -1))

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [11]:
a.reshape(-1, 2)

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [12]:
np.reshape (a, (-1, 6))

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

### 4 - Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

In [13]:
a.reshape(12, -1)

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [14]:
a.ndim

2

### ответ - нет

### 5 - Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [15]:
a = np.random.randn(3, 4)
print (a)

[[ 1.3874911   1.18792623 -0.41761147 -1.024716  ]
 [ 2.43789323  1.24566786  0.51005171 -0.1866607 ]
 [-0.30218391 -0.4772921  -1.13280762 -0.04150863]]


In [16]:
b = a.flatten()
print (b)

[ 1.3874911   1.18792623 -0.41761147 -1.024716    2.43789323  1.24566786
  0.51005171 -0.1866607  -0.30218391 -0.4772921  -1.13280762 -0.04150863]


In [17]:
a.size == b.size

True

### 6 - Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [18]:
a = np.arange (20, 0, -2)
print(a)

[20 18 16 14 12 10  8  6  4  2]


###  7 - Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [19]:
b = np.arange (20, 1, -2).reshape(1, 10)
print (b)

[[20 18 16 14 12 10  8  6  4  2]]


In [20]:
np.array_equal(a, b)

False

### ответ - а - одномерный массив, b - многомерный массив. Индексы элементов из а-массива: 0, 1, 2, 3,.. Индексы элементов  b-массива: 00, 01, 02, 03,...

### 8 -  Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [21]:
a = np.zeros ((2, 2))
b = np.ones ((3,2))
print('Массив a ', a, sep='\n')
print('Массив b ', b, sep='\n')

Массив a 
[[0. 0.]
 [0. 0.]]
Массив b 
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [22]:
v = np.concatenate((a, b), axis = 0)
print (v)
v.size

[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


10

### 9 - Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [23]:
a = np.arange (0, 12)
print (a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [24]:
A = a.reshape(4, 3)
print('Матрица А ', A, sep='\n')

Матрица А 
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [25]:
At = A.transpose()
print('Матрица Аt ', At, sep='\n')

Матрица Аt 
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [26]:
B = np.dot (A, At)
print('Матрица B ', B, sep='\n')

Матрица B 
[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]


### результат: при умножении матриц число строк итоговой матрицы (B) равно число строк первой матрицы (A), а число столбцов - второй матрицы (At).

In [27]:
B.size

16

In [28]:
np.linalg.det(B)

0.0

### Ответ: вычислить обратную матрицу для B невозможно, т.к. определитель матрицы B равен 0.

### 10 - Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [29]:
np.random.seed(42)

### 11 - Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 

In [30]:
a = np.random.randint(0, 16, 16)
print (a)

[ 6  3 12 14 10  7 12  4  6  9  2  6 10 10  7  4]


### 12 - Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [31]:
np.sqrt(a.size)

4.0

In [32]:
C = a.reshape((4, 4))
print('Матрица C ', C, sep='\n')
print('Матрица B ', B, sep='\n')
C.shape == B.shape

Матрица C 
[[ 6  3 12 14]
 [10  7 12  4]
 [ 6  9  2  6]
 [10 10  7  4]]
Матрица B 
[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]


True

In [33]:
D = B + C*10
print('Матрица D', D, sep='\n')

Матрица D
[[ 65  44 143 172]
 [114 120 206 162]
 [ 83 176 169 272]
 [132 222 282 342]]


In [34]:
np.linalg.det(D)

-28511999.999999944

In [35]:
np.linalg.matrix_rank(D, tol=None, hermitian=False)

4

In [36]:
D_inv = np.linalg.inv(D)
print('Матрица D_inv', D_inv, sep='\n')

Матрица D_inv
[[ 0.00935396  0.04486532  0.05897517 -0.07286055]
 [-0.01503577 -0.00122896 -0.00192971  0.00967873]
 [-0.00356692 -0.01782828 -0.04152146  0.04326178]
 [ 0.00909091 -0.00181818  0.01272727 -0.01090909]]


### Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [37]:
mask_positive = D_inv > 0
mask_negative = D_inv < 0
D_inv[mask_positive] = 1
D_inv[mask_negative] = 0
print(D_inv)

[[1. 1. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [1. 0. 1. 0.]]


In [38]:
E = np.where(D_inv, B, C)
print('Матрица E', E, sep='\n')

Матрица E
[[  5  14  23  14]
 [ 10   7  12 122]
 [  6   9   2 212]
 [ 32  10 212   4]]


In [39]:
E.shape

(4, 4)